server.port: 9090
spring:
  application:
    name: flugbuchungsapi
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/m295-project
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver